spring.application.name=CachingImplementation

spring.datasource.url=jdbc:mysql://localhost:3306/Caching
spring.datasource.username=root
spring.datasource.password=baGGa311@
spring.jpa.hibernate.ddl-auto=update

#redis configuration
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.data.redis.host=redis-18331.c264.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=18331
spring.data.redis.password=tKnWKzE0tiTlmAmkjlnXWKSxI5EbFUKO


spring.data.redis.ssl.enabled=false